#!/bin/bash
#
# 	prerm -- Pre removal script for appweb-doc
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

BLD_PRODUCT=!!BLD_PRODUCT!!
BLD_NAME="!!BLD_NAME!!"
BLD_PREFIX=!!BLD_PREFIX!!
BLD_DOC_PREFIX=!!BLD_DOC_PREFIX!!
BLD_SAM_PREFIX=!!BLD_SAM_PREFIX!!
BLD_SRC_PREFIX=!!BLD_SRC_PREFIX!!
BLD_HTTP_PORT=!!BLD_HTTP_PORT!!

###############################################################################

remove() {
	:
}


###############################################################################
#
#	Main
#
action=$1
cd /

case $action in
	remove)					# when new
		# or conflictor's prerm remove in-favor package new-version
		oldVersion=$2
		remove
		;;
	upgrade)				# when old
		newVersion=$2
		;;
	failed-upgrade)			# when new
		oldVersion=$2
		;;
	deconfigure)			# when old
		# 	deconfigure in-favor package-being-installed version removing 
		#	conflicting-package version
	esac
exit 0
